window.basicItemList = [
    {
        "name": "Amplifying Tome",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 20,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 435,
        "src": "amptome",
        "type": "basic"
    },
    {
        "name": "B. F. Sword",
        "ad": 40,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1300,
        "src": "bfsword",
        "type": "basic"
    },
    {
        "name": "Blasting Wand",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 40,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 850,
        "src": "blastingwand",
        "type": "basic"
    },
    {
        "name": "Cloak of Agility",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 15,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 600,
        "src": "cloak",
        "type": "basic"
    },
    {
        "name": "Cloth Armor",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 15,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 300,
        "src": "clotharmor",
        "type": "basic"
    },
    {
        "name": "Dagger",
        "ad": 0,
        "as": 12,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 300,
        "src": "dagger",
        "type": "basic"
    },
    {
        "name": "Faerie Charm",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 50,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 250,
        "src": "faeriecharm",
        "type": "basic"
    },
    {
        "name": "Long Sword",
        "ad": 10,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 300,
        "src": "longsword",
        "type": "basic"
    },
    {
        "name": "Needlessly Large Rod",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 60,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1250,
        "src": "largerod",
        "type": "basic"
    },
    {
        "name": "Null-Magic Mantle",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 25,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 450,
        "src": "nullmagic",
        "type": "basic"
    },
    {
        "name": "Pickaxe",
        "ad": 25,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 875,
        "src": "pickaxe",
        "type": "basic"
    },
    {
        "name": "Rejuvenation Bead",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 100,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 300,
        "src": "rejuvbead",
        "type": "basic"
    },
    {
        "name": "Ruby Crystal",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 150,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 400,
        "src": "rubycrystal",
        "type": "basic"
    },
    {
        "name": "Sapphire Crystal",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 250,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 350,
        "src": "sapphirecrystal",
        "type": "basic"
    },
    {
        "name": "Sheen",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 700,
        "src": "sheen",
        "type": "basic"
    },
    {
        "name": "Stopwatch",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 750,
        "src": "stopwatch",
        "type": "basic"
    },
];