window.bootsItemList = [
    {
        "name": "Berserkers Greaves",
        "ad": 0,
        "as": 35,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 45,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1100,
        "src": "berserkers",
        "type": "boots"
    },
    {
        "name": "Boots",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 25,
        "percentms": 0,
        "tenacity": 0,
        "cost": 300,
        "src": "boots",
        "type": "boots"
    },
    {
        "name": "Boots of Swiftness",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 60,
        "percentms": 0,
        "tenacity": 0,
        "cost": 900,
        "src": "swiftness",
        "type": "boots"
    },
    {
        "name": "Ionian Boots of Lucidity",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 45,
        "percentms": 0,
        "tenacity": 0,
        "cost": 950,
        "src": "ionian",
        "type": "boots"
    },
    {
        "name": "Mercury Treads",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 25,
        "ms": 45,
        "percentms": 0,
        "tenacity": 30,
        "cost": 1100,
        "src": "mercurys",
        "type": "boots"
    },
    {
        "name": "Mobility Boots",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 115,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1000,
        "src": "mobility",
        "type": "boots"
    },
    {
        "name": "Plated Steelcaps",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 20,
        "mr": 0,
        "ms": 45,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1100,
        "src": "tabis",
        "type": "boots"
    },
    {
        "name": "Sorcerers Shoes",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 18,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 45,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1100,
        "src": "sorcerers",
        "type": "boots"
    }
];