window.epicItemList = [
    {
        "name": "Aegis of the Legion",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 10,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 30,
        "mr": 30,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1200,
        "src": "aegis",
        "type": "epic"
    },
    {
        "name": "Aether Wisp",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 30,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 5,
        "tenacity": 0,
        "cost": 850,
        "src": "aetherwisp",
        "type": "epic"
    },
    {
        "name": "Bamis Cinder",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 300,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1000,
        "src": "bamis",
        "type": "epic"
    },
    {
        "name": "Bandleglass Mirror",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 20,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 10,
        "mana": 0,
        "manaregen": 50,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 950,
        "src": "bandleglass",
        "type": "epic"
    },
    {
        "name": "Blighting Jewel",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 25,
        "flatpen": 0,
        "magicpen": 13,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1250,
        "src": "blightingjewel",
        "type": "epic"
    },
    {
        "name": "Bramble Vest",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 30,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 800,
        "src": "bramble",
        "type": "epic"
    },
    {
        "name": "Catalyst of Aeons",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 300,
        "manaregen": 0,
        "healshield": 0,
        "hp": 300,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1300,
        "src": "catalyst",
        "type": "epic"
    },
    {
        "name": "Caulfields Warhammer",
        "ad": 25,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 10,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1100,
        "src": "caulfields",
        "type": "epic"
    },
    {
        "name": "Chain Vest",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 40,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 080,
        "src": "chainvest",
        "type": "epic"
    },
    {
        "name": "Crystalline Bracer",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 200,
        "hpregen": 100,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 800,
        "src": "bracer",
        "type": "epic"
    },
    {
        "name": "Executioners Calling",
        "ad": 15,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 800,
        "src": "executioners",
        "type": "epic"
    },
    {
        "name": "Fiendish Codex",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 35,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 10,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 900,
        "src": "fiendish",
        "type": "epic"
    },
    {
        "name": "Forbidden Idol",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 50,
        "healshield": 8,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 800,
        "src": "idol",
        "type": "epic"
    },
    {
        "name": "Frostfang",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 15,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 50,
        "healshield": 0,
        "hp": 70,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 400,
        "src": "frostfang",
        "type": "epic"
    },
    {
        "name": "Giants Belt",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 350,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 900,
        "src": "giantsbelt",
        "type": "epic"
    },
    {
        "name": "Glacial Buckler",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 10,
        "mana": 250,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 20,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 900,
        "src": "buckler",
        "type": "epic"
    },
    {
        "name": "Harrowing Crescent",
        "ad": 10,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 50,
        "healshield": 0,
        "hp": 60,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 400,
        "src": "harrowingcrescent",
        "type": "epic"
    },
    {
        "name": "Hearthbound Axe",
        "ad": 20,
        "as": 15,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1100,
        "src": "hearthbound",
        "type": "epic"
    },
    {
        "name": "Hexdrinker",
        "ad": 25,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 35,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1300,
        "src": "hexdrinker",
        "type": "epic"
    },
    {
        "name": "Hextech Alternator",
        "ad": 25,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 150,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1050,
        "src": "alternator",
        "type": "epic"
    },
    {
        "name": "Ironspike Whip",
        "ad": 30,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1100,
        "src": "whip",
        "type": "epic"
    },
    {
        "name": "Kindlegem",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 10,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 200,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 800,
        "src": "kindlegem",
        "type": "epic"
    },
    {
        "name": "Kircheis Shard",
        "ad": 15,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 700,
        "src": "kircheis",
        "type": "epic"
    },
    {
        "name": "Last Whisper",
        "ad": 20,
        "as": 0,
        "lethality": 0,
        "armorpen": 18,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1450,
        "src": "lastwhisper",
        "type": "epic"
    },
    {
        "name": "Leeching Leer",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 5,
        "crit": 0,
        "ap": 20,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 250,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1300,
        "src": "leechingleer",
        "type": "epic"
    },
    {
        "name": "Lost Chapter",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 40,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 10,
        "mana": 300,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1100,
        "src": "lostchapter",
        "type": "epic"
    },
    {
        "name": "Negatron Cloak",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 50,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 900,
        "src": "negatron",
        "type": "epic"
    },
    {
        "name": "Noonquiver",
        "ad": 30,
        "as": 15,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1300,
        "src": "noonquiver",
        "type": "epic"
    },
    {
        "name": "Oblivion Orb",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 30,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 800,
        "src": "oblivionorb",
        "type": "epic"
    },
    {
        "name": "Phage",
        "ad": 15,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 200,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1100,
        "src": "phage",
        "type": "epic"
    },
    {
        "name": "Quicksilver Sash",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 30,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1300,
        "src": "qss",
        "type": "epic"
    },
    {
        "name": "Rageknife",
        "ad": 0,
        "as": 25,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1200,
        "src": "rageknife",
        "type": "epic"
    },
    {
        "name": "Recurve Bow",
        "ad": 0,
        "as": 15,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 700,
        "src": "recurvebow",
        "type": "epic"
    },
    {
        "name": "Runesteel Spaulders",
        "ad": 6,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 100,
        "hpregen": 75,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 400,
        "src": "runesteel",
        "type": "epic"
    },
    {
        "name": "Seekers Armguard", // assume no stacks
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 30,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 15,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1000,
        "src": "seekers",
        "type": "epic"
    },
    {
        "name": "Serrated Dirk",
        "ad": 30,
        "as": 0,
        "lethality": 10,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1100,
        "src": "dirk",
        "type": "epic"
    },
    {
        "name": "Spectres Cowl",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 250,
        "hpregen": 0,
        "armor": 0,
        "mr": 25,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1250,
        "src": "spectres",
        "type": "epic"
    },
    {
        "name": "Targons Buckler",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 10,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 100,
        "hpregen": 75,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 400,
        "src": "targons",
        "type": "epic"
    },
    {
        "name": "Tiamat",
        "ad": 25,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1200,
        "src": "tiamat",
        "type": "epic"
    },
    {
        "name": "Vampiric Scepter",
        "ad": 15,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 7,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 900,
        "src": "vampiric",
        "type": "epic"
    },
    {
        "name": "Verdant Barrier", // assuming no stacks
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 20,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 25,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1000,
        "src": "verdant",
        "type": "epic"
    },
    {
        "name": "Wardens Mail",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 40,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1000,
        "src": "wardens",
        "type": "epic"
    },
    {
        "name": "Watchful Wardstone",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 10,
        "mana": 0,
        "manaregen": 50,
        "healshield": 0,
        "hp": 150,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1100,
        "src": "watchfulwardstone",
        "type": "epic"
    },
    {
        "name": "Winged Moonplate",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 150,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 5,
        "tenacity": 0,
        "cost": 800,
        "src": "moonplate",
        "type": "epic"
    },
    {
        "name": "Zeal",
        "ad": 0,
        "as": 15,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 15,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 5,
        "tenacity": 0,
        "cost": 1100,
        "src": "zeal",
        "type": "epic"
    },
    {
        "name": "Chalice of Blessing",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 50,
        "healshield": 0,
        "hp": 200,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 900,
        "src": "chaliceofblessing",
        "type": "epic"
    },
    {
        "name": "Lifewell Pendant",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 5,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 150,
        "hpregen": 0,
        "armor": 25,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1050,
        "src": "lifewellpendant",
        "type": "epic"
    }
];