window.legendaryItemList = [
    {
        "name": "Abyssal Mask",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 10,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 300,
        "hpregen": 0,
        "armor": 0,
        "mr": 60,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2400,
        "src": "abyssal",
        "type": "legendary"
    },
    {
        "name": "Anathemas Chains",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 650,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2500,
        "src": "chains",
        "type": "legendary"
    },
    {
        "name": "Archangels Staff",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 70,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 10,
        "mana": 500,
        "manaregen": 0,
        "healshield": 0,
        "hp": 200,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "archangels",
        "type": "legendary"
    },
    {
        "name": "Ardent Censer",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 35,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 75,
        "healshield": 8,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 5,
        "tenacity": 0,
        "cost": 2100,
        "src": "ardent",
        "type": "legendary"
    },
    {
        "name": "Axiom Arc",
        "ad": 55,
        "as": 0,
        "lethality": 18,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 25,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "axiomarc",
        "type": "legendary"
    },
    {
        "name": "Banshees Veil",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 80,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 10,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 45,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2600,
        "src": "banshees",
        "type": "legendary"
    },
    {
        "name": "Black Cleaver",
        "ad": 50,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 30,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 400,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3100,
        "src": "cleaver",
        "type": "legendary"
    },
    {
        "name": "Black Mist Scythe", // support item
        "ad": 20,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 100,
        "healshield": 0,
        "hp": 75,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 400,
        "src": "blackmistscythe",
        "type": "legendary"
    },
    {
        "name": "Blade of the Ruined King",
        "ad": 40,
        "as": 25,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 8,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3300,
        "src": "botrk",
        "type": "legendary"
    },
    {
        "name": "Bloodthirster", // assume with no bonus ad (need to implement on a level basis)
        "ad": 55,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 18,
        "omnivamp": 0,
        "crit": 20,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3200,
        "src": "bloodthirster",
        "type": "legendary"
    },
    {
        "name": "Bulwark of the Mountain",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 20,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 250,
        "hpregen": 100,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 400,
        "src": "bulwark",
        "type": "legendary"
    },
    {
        "name": "Chempunk Chainsword",
        "ad": 55,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 25,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 250,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2800,
        "src": "chainsword",
        "type": "legendary"
    },
    {
        "name": "Chemtech Putrifier",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 35,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 15,
        "mana": 0,
        "manaregen": 75,
        "healshield": 10,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2100,
        "src": "putrifier",
        "type": "legendary"
    },
    {
        "name": "Cosmic Drive",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 100,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 30,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 5,
        "tenacity": 0,
        "cost": 3000,
        "src": "cosmicdrive",
        "type": "legendary"
    },
    {
        "name": "Dead Mans Plate",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 300,
        "hpregen": 0,
        "armor": 45,
        "mr": 0,
        "ms": 0,
        "percentms": 5,
        "tenacity": 0,
        "cost": 2900,
        "src": "deadmans",
        "type": "legendary"
    },
    {
        "name": "Deaths Dance",
        "ad": 55,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 15,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 45,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3300,
        "src": "deathsdance",
        "type": "legendary"
    },
    {
        "name": "Demonic Embrace", // unique passive for increasing ap
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 75,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 350,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "demonicembrace",
        "type": "legendary"
    },
    {
        "name": "Edge of Night",
        "ad": 50,
        "as": 0,
        "lethality": 10,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 325,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2900,
        "src": "edgeofnight",
        "type": "legendary"
    },
    {
        "name": "Essence Reaver",
        "ad": 55,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 20,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2900,
        "src": "essence",
        "type": "legendary"
    },
    {
        "name": "Fimbulwinter",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 15,
        "mana": 860,
        "manaregen": 0,
        "healshield": 0,
        "hp": 400,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2600,
        "src": "fimbulwinter",
        "type": "legendary"
    },
    {
        "name": "Force of Nature",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 400,
        "hpregen": 0,
        "armor": 0,
        "mr": 60,
        "ms": 0,
        "percentms": 5,
        "tenacity": 0,
        "cost": 2800,
        "src": "forceofnature",
        "type": "legendary"
    },
    {
        "name": "Frozen Heart",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 400,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 90,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2700,
        "src": "frozenheart",
        "type": "legendary"
    },
    {
        "name": "Gargoyle Stoneplate",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 15,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 60,
        "mr": 60,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3200,
        "src": "gargoylestoneplate",
        "type": "legendary"
    },
    {
        "name": "Guardian Angel",
        "ad": 45,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 40,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "ga",
        "type": "legendary"
    },
    {
        "name": "Horizon Focus",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 100,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 15,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 150,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "horizon",
        "type": "legendary"
    },
    {
        "name": "Hullbreaker",
        "ad": 60,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 400,
        "hpregen": 150,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 5,
        "tenacity": 0,
        "cost": 3000,
        "src": "hullbreaker",
        "type": "legendary"
    },
    {
        "name": "Knights Vow",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 15,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 350,
        "hpregen": 125,
        "armor": 25,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2200,
        "src": "knightsvow",
        "type": "legendary"
    },
    {
        "name": "Lich Bane",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 85,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 15,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 8,
        "tenacity": 0,
        "cost": 3000,
        "src": "lichbane",
        "type": "legendary"
    },
    {
        "name": "Lord Dominiks Regards",
        "ad": 35,
        "as": 0,
        "lethality": 0,
        "armorpen": 30,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 20,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "lorddoms",
        "type": "legendary"
    },
    {
        "name": "Manamune",
        "ad": 35,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 15,
        "mana": 500,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2900,
        "src": "manamune",
        "type": "legendary"
    },
    {
        "name": "Maw of Malmortius",
        "ad": 65,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 50,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2800,
        "src": "maw",
        "type": "legendary"
    },
    {
        "name": "Mejais Soulstealer", // assuming no stacks
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 20,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 100,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 1600,
        "src": "mejais",
        "type": "legendary"
    },
    {
        "name": "Mercurial Scimitar",
        "ad": 40,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 20,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 50,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "scimitar",
        "type": "legendary"
    },
    {
        "name": "Mikaels Blessing",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 100,
        "healshield": 15,
        "hp": 250,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2300,
        "src": "mikaels",
        "type": "legendary"
    },
    {
        "name": "Morellonomicon",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 90,
        "flatpen": 10,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 200,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "morellos",
        "type": "legendary"
    },
    {
        "name": "Mortal Reminder",
        "ad": 40,
        "as": 0,
        "lethality": 0,
        "armorpen": 30,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 20,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "mortalreminder",
        "type": "legendary"
    },
    {
        "name": "Muramana",
        "ad": 35,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 15,
        "mana": 860,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2900,
        "src": "muramana",
        "type": "legendary"
    },
    {
        "name": "Nashors Tooth",
        "ad": 0,
        "as": 50,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 100,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 15,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3200,
        "src": "nashors",
        "type": "legendary"
    },
    {
        "name": "Pauldrons of Whiterock",
        "ad": 15,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 250,
        "hpregen": 100,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 400,
        "src": "pauldrons",
        "type": "legendary"
    },
    {
        "name": "Phantom Dancer",
        "ad": 20,
        "as": 30,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 20,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 7,
        "tenacity": 0,
        "cost": 2800,
        "src": "phantomdance",
        "type": "legendary"
    },
    {
        "name": "Rabadon's Deathcap",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 120,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3600,
        "src": "deathcap",
        "type": "legendary"
    },
    {
        "name": "Randuins Omen",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 400,
        "hpregen": 0,
        "armor": 60,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "randuins",
        "type": "legendary"
    },
    {
        "name": "Rapid Firecannon",
        "ad": 30,
        "as": 15,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 20,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 7,
        "tenacity": 0,
        "cost": 3000,
        "src": "rapidfire",
        "type": "legendary"
    },
    {
        "name": "Ravenous Hydra", // assuming 0 stacks
        "ad": 65,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 10,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 25,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3400,
        "src": "ravenous",
        "type": "legendary"
    },
    {
        "name": "Redemption",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 100,
        "healshield": 15,
        "hp": 250,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2300,
        "src": "redemption",
        "type": "legendary"
    },
    {
        "name": "Runaans Hurricane",
        "ad": 0,
        "as": 40,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 20,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 7,
        "tenacity": 0,
        "cost": 2800,
        "src": "runaans",
        "type": "legendary"
    },
    {
        "name": "Rylais Crystal Scepter",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 75,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 400,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2600,
        "src": "rylais",
        "type": "legendary"
    },
    {
        "name": "Seraphs Embrace",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 70,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 10,
        "mana": 860,
        "manaregen": 0,
        "healshield": 0,
        "hp": 200,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "seraphs",
        "type": "legendary"
    },
    {
        "name": "Serpents Fang",
        "ad": 55,
        "as": 0,
        "lethality": 12,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2600,
        "src": "serpents",
        "type": "legendary"
    },
    {
        "name": "Seryldas Grudge",
        "ad": 45,
        "as": 0,
        "lethality": 0,
        "armorpen": 30,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3200,
        "src": "seryldas",
        "type": "legendary"
    },
    {
        "name": "Shadowflame",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 100,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 200,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "shadowflame",
        "type": "legendary"
    },
    {
        "name": "Shard of True Ice",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 40,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 100,
        "healshield": 0,
        "hp": 75,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 400,
        "src": "shardoftrueice",
        "type": "legendary"
    },
    {
        "name": "Silvermere Dawn",
        "ad": 40,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 300,
        "hpregen": 0,
        "armor": 0,
        "mr": 40,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "silvermere",
        "type": "legendary"
    },
    {
        "name": "Spear of Shojin",
        "ad": 65,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 300,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3400,
        "src": "shojin",
        "type": "legendary"
    },
    {
        "name": "Spirit Visage",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 10,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 450,
        "hpregen": 100,
        "armor": 0,
        "mr": 50,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2900,
        "src": "spiritvisage",
        "type": "legendary"
    },
    {
        "name": "Staff of Flowing Water",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 35,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 75,
        "healshield": 8,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 5,
        "tenacity": 0,
        "cost": 2100,
        "src": "staff",
        "type": "legendary"
    },
    {
        "name": "Steraks Gage",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 400,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3100,
        "src": "steraks",
        "type": "legendary"
    },
    {
        "name": "Stormrazor",
        "ad": 55,
        "as": 15,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 20,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "stormrazor",
        "type": "legendary"
    },
    {
        "name": "Sunfire Aegis",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 500,
        "hpregen": 0,
        "armor": 50,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2700,
        "src": "sunfire",
        "type": "legendary"
    },
    {
        "name": "The Collector",
        "ad": 55,
        "as": 0,
        "lethality": 18,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 20,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "collector",
        "type": "legendary"
    },
    {
        "name": "Thornmail",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 350,
        "hpregen": 0,
        "armor": 70,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2700,
        "src": "thornmail",
        "type": "legendary"
    },
    {
        "name": "Titanic Hydra",
        "ad": 30,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 500,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3300,
        "src": "titanic",
        "type": "legendary"
    },
    {
        "name": "Turbo Chemtank",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 10,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 500,
        "hpregen": 0,
        "armor": 0,
        "mr": 50,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 0,
        "src": "chemtank",
        "type": "legendary"
    },
    {
        "name": "Umbral Glaive",
        "ad": 50,
        "as": 0,
        "lethality": 10,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 15,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2300,
        "src": "umbral",
        "type": "legendary"
    },
    {
        "name": "Vigilant Wardstone",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 10,
        "mana": 0,
        "manaregen": 50,
        "healshield": 0,
        "hp": 250,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2300,
        "src": "vigilantwardstone",
        "type": "legendary"
    },
    {
        "name": "Void Staff",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 65,
        "flatpen": 0,
        "magicpen": 40,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2800,
        "src": "voidstaff",
        "type": "legendary"
    },
    {
        "name": "Warmogs Armor",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 10,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 800,
        "hpregen": 200,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "warmogs",
        "type": "legendary"
    },
    {
        "name": "Winters Approach",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 15,
        "mana": 500,
        "manaregen": 0,
        "healshield": 0,
        "hp": 400,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2600,
        "src": "wintersapproach",
        "type": "legendary"
    },
    {
        "name": "Wits End",
        "ad": 40,
        "as": 40,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 40,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3100,
        "src": "witsend",
        "type": "legendary"
    },
    {
        "name": "Zekes Convergence",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 15,
        "mana": 250,
        "manaregen": 0,
        "healshield": 0,
        "hp": 200,
        "hpregen": 0,
        "armor": 45,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2200,
        "src": "zekes",
        "type": "legendary"
    },
    {
        "name": "Zhonyas Hourglass",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 80,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 15,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 45,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "zhonyas",
        "type": "legendary"
    },
    {
        "name": "Kraken Slayer",
        "ad": 40,
        "as": 30,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 20,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "kraken",
        "type": "legendary"
    },
    {
        "name": "Immortal Shieldbow",
        "ad": 50,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 7,
        "omnivamp": 0,
        "crit": 20,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "shieldbow",
        "type": "legendary"
    },
    {
        "name": "Prowlers Claw",
        "ad": 55,
        "as": 0,
        "lethality": 15,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 15,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "prowlers",
        "type": "legendary"
    },
    {
        "name": "Statikk Shiv",
        "ad": 45,
        "as": 25,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 20,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "shiv",
        "type": "legendary"
    },
    {
        "name": "Imperial Mandate",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 55,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 100,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2300,
        "src": "mandate",
        "type": "legendary"
    },
];