window.mythicItemList = [
    {
        "name": "Crown of the Shattered Queen",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 70,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 600,
        "manaregen": 0,
        "healshield": 0,
        "hp": 250,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2800,
        "src": "crown",
        "type": "mythic"
    },
    {
        "name": "Divine Sunderer",
        "ad": 40,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 300,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3300,
        "src": "sunderer",
        "type": "mythic"
    },
    {
        "name": "Duskblade of Draktharr",
        "ad": 60,
        "as": 0,
        "lethality": 18,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3100,
        "src": "duskblade",
        "type": "mythic"
    },
    {
        "name": "Eclipse",
        "ad": 60,
        "as": 0,
        "lethality": 12,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 15,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3100,
        "src": "eclipse",
        "type": "mythic"
    },
    {
        "name": "Evenshroud",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 200,
        "hpregen": 0,
        "armor": 30,
        "mr": 30,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2300,
        "src": "evenshroud",
        "type": "mythic"
    },
    {
        "name": "Everfrost",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 70,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 600,
        "manaregen": 0,
        "healshield": 0,
        "hp": 250,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2800,
        "src": "everfrost",
        "type": "mythic"
    },
    {
        "name": "Galeforce",
        "ad": 55,
        "as": 15,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 20,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 7,
        "tenacity": 0,
        "cost": 3400,
        "src": "galeforce",
        "type": "mythic"
    },
    {
        "name": "Goredrinker",
        "ad": 55,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 8,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 300,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3200,
        "src": "goredrinker",
        "type": "mythic"
    },
    {
        "name": "Heartsteel",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 800,
        "hpregen": 200,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3200,
        "src": "heartsteel",
        "type": "mythic"
    },
    {
        "name": "Hextech Rocketbelt",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 90,
        "flatpen": 0,
        "magicpen": 6,
        "haste": 15,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 250,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3200,
        "src": "protobelt",
        "type": "mythic"
    },
    {
        "name": "Iceborn Gauntlet",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 400,
        "hpregen": 0,
        "armor": 50,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3000,
        "src": "iceborn",
        "type": "mythic"
    },
    {
        "name": "JakSho, The Protean",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 400,
        "hpregen": 0,
        "armor": 30,
        "mr": 30,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3200,
        "src": "jaksho",
        "type": "mythic"
    },

    {
        "name": "Liandrys Anguish",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 80,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 600,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3200,
        "src": "liandrys",
        "type": "mythic"
    },
    {
        "name": "Locket of the Iron Solari",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 200,
        "hpregen": 0,
        "armor": 30,
        "mr": 30,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2300,
        "src": "locket",
        "type": "mythic"
    },
    {
        "name": "Ludens Tempest",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 80,
        "flatpen": 6,
        "magicpen": 0,
        "haste": 20,
        "mana": 600,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3200,
        "src": "ludens",
        "type": "mythic"
    },
    {
        "name": "Moonstone Renewer",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 35,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 100,
        "healshield": 0,
        "hp": 200,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2300,
        "src": "moonstone",
        "type": "mythic"
    },
    {
        "name": "Night Harvester",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 90,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 25,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 300,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3200,
        "src": "nightharvester",
        "type": "mythic"
    },
    {
        "name": "Radiant Virtue",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 10,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 350,
        "hpregen": 0,
        "armor": 30,
        "mr": 30,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2700,
        "src": "radiant",
        "type": "mythic"
    },
    {
        "name": "Riftmaker",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 7,
        "crit": 0,
        "ap": 70,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 15,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 300,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3200,
        "src": "riftmaker",
        "type": "mythic"
    },
    {
        "name": "Rod of Ages", // at full stacks
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 100,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 600,
        "manaregen": 0,
        "healshield": 0,
        "hp": 600,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2800,
        "src": "rodofages",
        "type": "mythic"
    },
    {
        "name": "Shurelyas Battlesong",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 35,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 100,
        "healshield": 0,
        "hp": 200,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2300,
        "src": "shurelyas",
        "type": "mythic"
    },
    {
        "name": "Stridebreaker",
        "ad": 60,
        "as": 20,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 300,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3300,
        "src": "stridebreaker",
        "type": "mythic"
    },
    {
        "name": "Trinity Force",
        "ad": 40,
        "as": 35,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 300,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3333,
        "src": "trinityforce",
        "type": "mythic"
    },
    {
        "name": "Infinity Edge",
        "ad": 70,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 20,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3400,
        "src": "infinityedge",
        "type": "mythic"
    },
    {
        "name": "Navori Quickblades",
        "ad": 60,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 20,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3400,
        "src": "quickblades",
        "type": "mythic"
    },
    {
        "name": "Guinsoos Rageblade",
        "ad": 30,
        "as": 25,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 30,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3200,
        "src": "rageblade",
        "type": "mythic"
    },
    {
        "name": "Youmuus Ghostblade",
        "ad": 60,
        "as": 0,
        "lethality": 18,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 20,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 3100,
        "src": "youmuus",
        "type": "mythic"
    },
    {
        "name": "Echoes of Helia",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 30,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 15,
        "mana": 0,
        "manaregen": 125,
        "healshield": 0,
        "hp": 200,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 2300,
        "src": "echoesofhelia",
        "type": "mythic"
    }
];