window.starterItemList = [
    {
        "name": "Cull",
        "ad": 7,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 450,
        "src": "cull",
        "type": "starter"
    },
    {
        "name": "Dark Seal", // assuming no stacks
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 15,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 40,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 350,
        "src": "darkseal",
        "type": "starter"
    },
    {
        "name": "Dorans Blade",
        "ad": 8,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 80,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 450,
        "src": "doransblade",
        "type": "starter"
    },
    {
        "name": "Dorans Ring",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 15,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 70,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 400,
        "src": "doransring",
        "type": "starter"
    },
    {
        "name": "Dorans Shield",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 80,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 450,
        "src": "doransshield",
        "type": "starter"
    },
    {
        "name": "Relic Shield",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 5,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 30,
        "hpregen": 50,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 400,
        "src": "relicshield",
        "type": "starter"
    },
    {
        "name": "Spectral Sickle",
        "ad": 5,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 25,
        "healshield": 0,
        "hp": 10,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 400,
        "src": "spectralsickle",
        "type": "starter"
    },
    {
        "name": "Spellthiefs Edge",
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 8,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 25,
        "healshield": 0,
        "hp": 10,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 400,
        "src": "spellthiefs",
        "type": "starter"
    },
    {
        "name": "Steel Shoulderguards",
        "ad": 3,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 0,
        "manaregen": 0,
        "healshield": 0,
        "hp": 30,
        "hpregen": 50,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 400,
        "src": "shoulderguards",
        "type": "starter"
    },
    {
        "name": "Tear of the Goddess", // assume no stacks
        "ad": 0,
        "as": 0,
        "lethality": 0,
        "armorpen": 0,
        "lifesteal": 0,
        "omnivamp": 0,
        "crit": 0,
        "ap": 0,
        "flatpen": 0,
        "magicpen": 0,
        "haste": 0,
        "mana": 240,
        "manaregen": 0,
        "healshield": 0,
        "hp": 0,
        "hpregen": 0,
        "armor": 0,
        "mr": 0,
        "ms": 0,
        "percentms": 0,
        "tenacity": 0,
        "cost": 400,
        "src": "tear",
        "type": "starter"
    }
];